#! /bin/sh

bspc config border_width            3
bspc config window_gap              10
bspc config split_ratio             0.50

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config single_monocle          false
bspc config focus_follows_pointer   false

# Borders
bspc config focused_border_color    "#7aa2f7"
bspc config normal_border_color     "#32344a"
bspc config active_border_color     "#444b6a"


#
# Autostart
#

# Kill if already running
killall -9 picom sxhkd dunst ksuperkey volumeicon

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# start compositor
picom --config $HOME/.config/picom.conf &

# Set display from arandr
bash $HOME/.screenlayout/layout.sh

# Polybar
$HOME/.config/polybar/launch.sh

# polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Restore wallpaper
nitrogen --restore &

# Network manager
nm-applet &

# Volumeicon
volumeicon &

# numlockx
numlockx on &

# Launch notification daemon
dunst -config $HOME/.config/dunstrc &

# fix cusrsor
xsetroot -cursor_name left_ptr


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Set workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
		let name++
	done
}
workspaces


# Run IBUS Deamon
ibus-daemon -drxR
setxkbmap -option grp:alt_shift_toggle il,us,ru &

# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(google-chrome)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Pcmanfm)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
"VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr Pavucontrol)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Lxappearance Arandr)
for i in ${floats[@]}; do
    bspc rule -a $i state=floating follow=on focus=on; done
